src/Entity/Experiences.php
<?php

namespace App\Entity;

use App\Repository\ExperiencesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExperiencesRepository::class)
 */
class Experiences
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\ManyToMany(targetEntity=Entreprises::class, inversedBy="experiences")
     */
    private $entreprises;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="experiences")
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprises_txt;

    public function __construct()
    {
        $this->entreprises = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return Collection|Entreprises[]
     */
    public function getEntreprises(): Collection
    {
        return $this->entreprises;
    }

    public function addEntreprise(Entreprises $entreprise): self
    {
        if (!$this->entreprises->contains($entreprise)) {
            $this->entreprises[] = $entreprise;
        }

        return $this;
    }

    public function removeEntreprise(Entreprises $entreprise): self
    {
        $this->entreprises->removeElement($entreprise);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEntreprisesTxt(): ?string
    {
        return $this->entreprises_txt;
    }

    public function setEntreprisesTxt(string $entreprises_txt): self
    {
        $this->entreprises_txt = $entreprises_txt;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Entity\Categories;
use App\Entity\Competences;
use App\Entity\User;
use App\Form\AdresseType;
use App\Form\UserType;
use App\Repository\CompetencesRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfilController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    public function __construct(EntityManagerInterface $entityManager, UserRepository $userRepository, CompetencesRepository $CompetencesRepository){
        $this -> entityManager = $entityManager;
        $this -> userRepository = $userRepository;
        $this -> CompetencesRepository = $CompetencesRepository;

    }

    /**
     * @Route("/profil", name="profil")
     */
    public function index(): Response
    {
        $user = $this->entityManager->getRepository(User::class)->findAll();
        $competences = $this->entityManager->getRepository(Competences::class)->findAll();
        $categories = $this->entityManager->getRepository(Categories::class)->findAll();

        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
            'user' => $user,
            'competences' => $competences,
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/profil/show", name="show")
     */
    public function show(): Response
    {
        $user = $this->entityManager->getRepository(User::class)->findAll();
        $competences = $this->entityManager->getRepository(Competences::class)->findAll();
        $categories = $this->entityManager->getRepository(Categories::class)->findAll();

        return $this->render('profil/show.html.twig', [
            'controller_name' => 'ProfilController',
            'user' => $user,
            'userListe' => $this->userRepository->findAll(),
            'competences' => $competences,
            'categories' => $categories,
        ]);
    }


    /**
     * @Route("/register/{id}/edit", name="editprofil")
     */
    public function edit(User $profil, UserPasswordEncoderInterface $passwordEncoder, Request $request)
    : Response {
        $form = $this->createForm(UserType::class, $profil);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $profil = $form->getData();

            // Encoder le mot de passe
            $profil->setPassword($passwordEncoder->encodePassword($profil, $profil->getPassword()));

            $this->entityManager->persist($profil);
            $this->entityManager->flush();

            return $this->redirectToRoute('profil');
        }

        return $this->render(
            'register/index.html.twig',
            ['form' => $form->createView()]
        );
    }


}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <style>
        .container { margin: 2em auto 5em auto; max-width: 1000px; width: 95%; font: 18px/1.5 sans-serif; }
        .flex { display: flex; }
        .head { justify-content: space-between; align-items: center; }
        * { margin: 0; }
        p.role { margin-top: 5px; }
        p.link-dashboard { margin: 40px 0; }
        .profil { justify-content: space-around; border: 1px solid darkslategrey; padding: 20px; margin-top: 25px; }
        .competences, .experiences { margin: 30px 0 30px 15px; }
    </style>

    <div class="container">
        <div class="head flex">
            <h1>Bienvenue {{ app.user.prenom }} {{ app.user.nom }}</h1>
            <p><a class="inscription-button" href="{{ path('app_logout') }}">Se déconnecter</a></p>
        </div>

        <p class="role"><small> Profil <i>
            {% if is_granted("ROLE_CANDIDAT") %}candidat{% endif %}
            {% if is_granted("ROLE_COLLABORATEUR") %}collaborateur{% endif %}
            {% if is_granted("ROLE_ADMIN") %}administrateur{% endif %}</i></small>
        </p>

        {% if is_granted("ROLE_ADMIN") %}
            <p class="link-dashboard">Connection au <a class="lien" href="{{ path('dashboard') }}">dashboard</a></p>
        {% endif %}

        <div class="profil flex">
            <div class="informations">
                <h2>Mes informations</h2>
                <ul>
                    <li>Nom : {{ app.user.nom }}</li>
                    <li>Prénom : {{ app.user.prenom }}</li>
                    <li>E-mail : {{ app.user.email }}</li>
                    {% if app.user.adresse %}
                    <li>Numéro : {{ app.user.adresse.telephone }}</li>
                    {% endif %}
                </ul>

                <p>Modifier mes infos : <a href="{{ path('editprofil', {'id': app.user.id}) }}">ici</a></p>
            </div>

            <div class="adresse">
                {% if app.user.adresse %}
                    <h2>Mon adresse</h2>
                    <ul>
                        <li>Numéro : {{ app.user.adresse.numero }}</li>
                        <li>Adresse : {{ app.user.adresse.adresse }}</li>
                        <li>Code postal : {{ app.user.adresse.codePostal }}</li>
                        <li>Ville : {{ app.user.adresse.ville }}</li>
                    </ul>

                    <p>Modifier mon adresse : <a href="{{ path('editadresse', {'id': app.user.adresse.id})}}">ici</a> </p>
                {% else %}
                    <i>Compléter mon profil : <a href="{{ path('newadresse', {'id': app.user.id})}}">ici</a> </i>
                {% endif %}
            </div>
        </div>

        {% if is_granted("ROLE_COLLABORATEUR") %}
            <div class="competences">
                <h2>Mes compétences</h2>
                <p>Ajouter de nouvelles compétences : <a href="{{ path('newCompetences', {'id': app.user.id})}}">ici</a> </p>
                {% if app.user.competences %}
                <ul>{% for competences in app.user.competences %}
                        <li>{% if competences.aime %}
                                <small>♥</small>
                            {% else %}
                                <small>♡</small>
                            {% endif %} {{ competences.nom}} - Niveau : {{ competences.niveau}} - <small><a href="{{ path('editCompetences', {'id': competences.id})}}" >éditer</a> </small></li>

                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="experiences">
                <h2>Mes expériences</h2>
                <p>Ajouter de nouvelles expériences : <a href="{{ path('newExperiences', {'id': app.user.id})}}">ici</a> </p>
                {% if app.user.experiences %}
                <ul>{% for experience in app.user.experiences %}
                        <li>{{ experience.nom}} à {{ experience.entreprisesTxt}} - <small><a href="{{ path('editExperiences', {'id': experience.id})}}">éditer</a></small>
                            <p>{{ experience.description}}</p></li>

                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/profil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profils complets{% endblock %}

{% block body %}
    <style>
        .container { margin: 0 auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
        h1 { text-align: center; }
        .flex { display: flex;}
        .usersListe { flex-wrap: wrap; justify-content: space-around; margin: 0 auto; }
        .cards { width: 475px; border: 1px solid darkslategrey; margin: 15px; padding: 15px; }
        ul, p { margin: 0; }
    </style>

    <span><i><a href="{{ path('dashboard') }}">Retour au dashboard</a></i></span>

    <div class="container">
        <h1>Profils complets des utilisateurs</h1>

        <div class="usersListe flex">
            {% for user in userListe %}
            <div class="cards">
                <ul>
                    <li>Id : {{ user.id }}</li>
                    <li>Nom : {{ user.nom }}</li>
                    <li>Prénom : {{ user.prenom }}</li>
                    <li>Email : {{ user.email }}</li>
                    {% if user.adresse %}
                        {% if user.adresse.telephone %}
                            <li>Téléphone : {{ user.adresse.telephone }}</li>
                        {% endif %}
                        <li>
                            Adresse :
                            <ul>
                                <li>{{ user.adresse.numero }} {{ user.adresse.adresse }}</li>
                                <li>{{ user.adresse.codePostal }} {{ user.adresse.ville }}</li>
                            </ul>
                        </li>
                    {% endif %}
                    <br>
                    <li>
                        Compétences :
                        {% if user.competences %}
                        <ul>
                            {% for competences in user.competences %}
                                <li>{% if competences.aime %} ♥ {% else%} ♡{% endif %}
                                    {{ competences.nom}} -
                                    Niveau : {{ competences.niveau}}
                                </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            <span>Aucune expérience spécifiée</span>
                        {% endif %}
                    </li>
                    <li>
                        Expériences :
                        <ul>
                            {% for experiences in user.experiences %}
                                <li>
                                    <p>Libellé : {{ experiences.nom }}</p>
                                    <p>Entreprise : {{ experiences.entreprisesTxt }}</p>
                                    <p>Description : {{ experiences.description }}</p>
                                </li>
                            {% endfor %}
                        </ul>

                    </li>




                    </li>
                </ul>
            </div>
            {% endfor %}
        </div>



    </div>




{% endblock %}